//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gw2lav.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gw2lav.Properties.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary Armory Viewer.
        /// </summary>
        public static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string btn_apply {
            get {
                return ResourceManager.GetString("btn_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string btn_update {
            get {
                return ResourceManager.GetString("btn_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load detail information. This probably means that your Guild Wars 2 Api Key is not set or that it has insufficient permissions. Please check Settings..
        /// </summary>
        public static string detail_error {
            get {
                return ResourceManager.GetString("detail_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select any Legendary item to view details here.
        /// </summary>
        public static string detail_message {
            get {
                return ResourceManager.GetString("detail_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquire for.
        /// </summary>
        public static string detail_needed {
            get {
                return ResourceManager.GetString("detail_needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for.
        /// </summary>
        public static string detail_usable {
            get {
                return ResourceManager.GetString("detail_usable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used on.
        /// </summary>
        public static string detail_used {
            get {
                return ResourceManager.GetString("detail_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal notice.
        /// </summary>
        public static string info_legal {
            get {
                return ResourceManager.GetString("info_legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2021 NCSOFT Corporation. All rights reserved. NCSOFT, ArenaNet, the interlocking NC logo, Guild Wars, Guild Wars 2: Heart of Thorns, Guild Wars 2: Path of Fire, and all associated logos, designs, and composite marks are trademarks or registered trademarks of NCSOFT Corporation. All other trademarks are the property of their respective owners..
        /// </summary>
        public static string info_legal_ncsoft {
            get {
                return ResourceManager.GetString("info_legal_ncsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info_title {
            get {
                return ResourceManager.GetString("info_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer version {0} is available!.
        /// </summary>
        public static string info_update_available {
            get {
                return ResourceManager.GetString("info_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string info_updating {
            get {
                return ResourceManager.GetString("info_updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version.
        /// </summary>
        public static string info_version {
            get {
                return ResourceManager.GetString("info_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Legendary Armory data.
        /// </summary>
        public static string main_error {
            get {
                return ResourceManager.GetString("main_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions needed: account, unlocks, inventories, characters.
        /// </summary>
        public static string settings_apikey_message {
            get {
                return ResourceManager.GetString("settings_apikey_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Wars 2 Api Key.
        /// </summary>
        public static string settings_apikey_title {
            get {
                return ResourceManager.GetString("settings_apikey_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show aquatic information.
        /// </summary>
        public static string settings_nowater_message {
            get {
                return ResourceManager.GetString("settings_nowater_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string settings_other {
            get {
                return ResourceManager.GetString("settings_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings_title {
            get {
                return ResourceManager.GetString("settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory.
        /// </summary>
        public static string type_accessory {
            get {
                return ResourceManager.GetString("type_accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amulet.
        /// </summary>
        public static string type_amulet {
            get {
                return ResourceManager.GetString("type_amulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquatic.
        /// </summary>
        public static string type_aquatic {
            get {
                return ResourceManager.GetString("type_aquatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coat.
        /// </summary>
        public static string type_armor_body {
            get {
                return ResourceManager.GetString("type_armor_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Coat.
        /// </summary>
        public static string type_armor_body_heavy {
            get {
                return ResourceManager.GetString("type_armor_body_heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Coat.
        /// </summary>
        public static string type_armor_body_light {
            get {
                return ResourceManager.GetString("type_armor_body_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Coat.
        /// </summary>
        public static string type_armor_body_medium {
            get {
                return ResourceManager.GetString("type_armor_body_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boots.
        /// </summary>
        public static string type_armor_feet {
            get {
                return ResourceManager.GetString("type_armor_feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Boots.
        /// </summary>
        public static string type_armor_feet_heavy {
            get {
                return ResourceManager.GetString("type_armor_feet_heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Boots.
        /// </summary>
        public static string type_armor_feet_light {
            get {
                return ResourceManager.GetString("type_armor_feet_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Boots.
        /// </summary>
        public static string type_armor_feet_medium {
            get {
                return ResourceManager.GetString("type_armor_feet_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloves.
        /// </summary>
        public static string type_armor_hands {
            get {
                return ResourceManager.GetString("type_armor_hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Gloves.
        /// </summary>
        public static string type_armor_hands_heavy {
            get {
                return ResourceManager.GetString("type_armor_hands_heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Gloves.
        /// </summary>
        public static string type_armor_hands_light {
            get {
                return ResourceManager.GetString("type_armor_hands_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Gloves.
        /// </summary>
        public static string type_armor_hands_medium {
            get {
                return ResourceManager.GetString("type_armor_hands_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helm.
        /// </summary>
        public static string type_armor_head {
            get {
                return ResourceManager.GetString("type_armor_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Helm.
        /// </summary>
        public static string type_armor_head_heavy {
            get {
                return ResourceManager.GetString("type_armor_head_heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Helm.
        /// </summary>
        public static string type_armor_head_light {
            get {
                return ResourceManager.GetString("type_armor_head_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Helm.
        /// </summary>
        public static string type_armor_head_medium {
            get {
                return ResourceManager.GetString("type_armor_head_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Armor.
        /// </summary>
        public static string type_armor_heavy {
            get {
                return ResourceManager.GetString("type_armor_heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leggings.
        /// </summary>
        public static string type_armor_legs {
            get {
                return ResourceManager.GetString("type_armor_legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Leggings.
        /// </summary>
        public static string type_armor_legs_heavy {
            get {
                return ResourceManager.GetString("type_armor_legs_heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Leggings.
        /// </summary>
        public static string type_armor_legs_light {
            get {
                return ResourceManager.GetString("type_armor_legs_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Leggings.
        /// </summary>
        public static string type_armor_legs_medium {
            get {
                return ResourceManager.GetString("type_armor_legs_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Armor.
        /// </summary>
        public static string type_armor_light {
            get {
                return ResourceManager.GetString("type_armor_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Armor.
        /// </summary>
        public static string type_armor_medium {
            get {
                return ResourceManager.GetString("type_armor_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulders.
        /// </summary>
        public static string type_armor_shoulders {
            get {
                return ResourceManager.GetString("type_armor_shoulders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Shoulders.
        /// </summary>
        public static string type_armor_shoulders_heavy {
            get {
                return ResourceManager.GetString("type_armor_shoulders_heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Shoulders.
        /// </summary>
        public static string type_armor_shoulders_light {
            get {
                return ResourceManager.GetString("type_armor_shoulders_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Shoulders.
        /// </summary>
        public static string type_armor_shoulders_medium {
            get {
                return ResourceManager.GetString("type_armor_shoulders_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Item.
        /// </summary>
        public static string type_back {
            get {
                return ResourceManager.GetString("type_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        public static string type_ring {
            get {
                return ResourceManager.GetString("type_ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune.
        /// </summary>
        public static string type_rune {
            get {
                return ResourceManager.GetString("type_rune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigil.
        /// </summary>
        public static string type_sigil {
            get {
                return ResourceManager.GetString("type_sigil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrestrial.
        /// </summary>
        public static string type_terrestrial {
            get {
                return ResourceManager.GetString("type_terrestrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinkets.
        /// </summary>
        public static string type_trinkets {
            get {
                return ResourceManager.GetString("type_trinkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string type_unknown {
            get {
                return ResourceManager.GetString("type_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrades.
        /// </summary>
        public static string type_upgrades {
            get {
                return ResourceManager.GetString("type_upgrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquatic
        ///weapons.
        /// </summary>
        public static string type_weapon_aquatic {
            get {
                return ResourceManager.GetString("type_weapon_aquatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe.
        /// </summary>
        public static string type_weapon_axe {
            get {
                return ResourceManager.GetString("type_weapon_axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagger.
        /// </summary>
        public static string type_weapon_dagger {
            get {
                return ResourceManager.GetString("type_weapon_dagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string type_weapon_focus {
            get {
                return ResourceManager.GetString("type_weapon_focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greatsword.
        /// </summary>
        public static string type_weapon_greatsword {
            get {
                return ResourceManager.GetString("type_weapon_greatsword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hammer.
        /// </summary>
        public static string type_weapon_hammer {
            get {
                return ResourceManager.GetString("type_weapon_hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spear.
        /// </summary>
        public static string type_weapon_harpoon {
            get {
                return ResourceManager.GetString("type_weapon_harpoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Bow.
        /// </summary>
        public static string type_weapon_longbow {
            get {
                return ResourceManager.GetString("type_weapon_longbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mace.
        /// </summary>
        public static string type_weapon_mace {
            get {
                return ResourceManager.GetString("type_weapon_mace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-handed weapons
        ///(Each hand).
        /// </summary>
        public static string type_weapon_onehand_each {
            get {
                return ResourceManager.GetString("type_weapon_onehand_each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-handed weapons
        ///(Single hand).
        /// </summary>
        public static string type_weapon_onehand_single {
            get {
                return ResourceManager.GetString("type_weapon_onehand_single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol.
        /// </summary>
        public static string type_weapon_pistol {
            get {
                return ResourceManager.GetString("type_weapon_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rifle.
        /// </summary>
        public static string type_weapon_rifle {
            get {
                return ResourceManager.GetString("type_weapon_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scepter.
        /// </summary>
        public static string type_weapon_scepter {
            get {
                return ResourceManager.GetString("type_weapon_scepter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        public static string type_weapon_shield {
            get {
                return ResourceManager.GetString("type_weapon_shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Bow.
        /// </summary>
        public static string type_weapon_shortbow {
            get {
                return ResourceManager.GetString("type_weapon_shortbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harpoon Gun.
        /// </summary>
        public static string type_weapon_speargun {
            get {
                return ResourceManager.GetString("type_weapon_speargun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string type_weapon_staff {
            get {
                return ResourceManager.GetString("type_weapon_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword.
        /// </summary>
        public static string type_weapon_sword {
            get {
                return ResourceManager.GetString("type_weapon_sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torch.
        /// </summary>
        public static string type_weapon_torch {
            get {
                return ResourceManager.GetString("type_weapon_torch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trident.
        /// </summary>
        public static string type_weapon_trident {
            get {
                return ResourceManager.GetString("type_weapon_trident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-handed weapons.
        /// </summary>
        public static string type_weapon_twohand {
            get {
                return ResourceManager.GetString("type_weapon_twohand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warhorn.
        /// </summary>
        public static string type_weapon_warhorn {
            get {
                return ResourceManager.GetString("type_weapon_warhorn", resourceCulture);
            }
        }
    }
}
